---

- name: "Check if APACHE is installed"
  package_facts:
    manager: "auto"

- name: debug
  debug:
    msg: "{{ ansible_os_family }}"

- name: "Apache or nginix result"
  debug:
    msg: "Webserver found"
  when:
     - "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"

- name: "Apache result"
  debug:
    msg: "Webserver NOT found"
  when:
    - "'apache2' not in ansible_facts.packages and 'nginx' not in ansible_facts.packages"
- name: Installing webserver
  apt:
    name: "{{ debian_webserver }}"
    state: present
  when: "'apache2' not in ansible_facts.packages and 'nginx' not in ansible_facts.packages"
  notify: start webserver

- name: 'Restart Webserver if Found'
  service:
    name: "{% if 'apache2' in ansible_facts.packages %}apache2{% else %}'nginx'{% endif %}"
    state: restarted
  when: "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"
